name: Deploy Laravel to Azure Web App

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # o la versión que uses
        extensions: mbstring, xml, bcmath, ctype, json, tokenizer
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Upload artifacts (optional)
      uses: actions/upload-artifact@v3
      with:
        name: vendor
        path: vendor

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'NOMBRE_DE_TU_APP_AZURE'  # cambia esto
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
